/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewsIndexRouteImport } from './routes/reviews.index'
import { Route as ReviewsReviewIdRouteImport } from './routes/reviews.$reviewId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsIndexRoute = ReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsReviewIdRoute = ReviewsReviewIdRouteImport.update({
  id: '/reviews/$reviewId',
  path: '/reviews/$reviewId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reviews/$reviewId': typeof ReviewsReviewIdRoute
  '/reviews/': typeof ReviewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reviews/$reviewId': typeof ReviewsReviewIdRoute
  '/reviews': typeof ReviewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reviews/$reviewId': typeof ReviewsReviewIdRoute
  '/reviews/': typeof ReviewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/reviews/$reviewId' | '/reviews/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/reviews/$reviewId' | '/reviews'
  id: '__root__' | '/' | '/reviews/$reviewId' | '/reviews/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReviewsReviewIdRoute: typeof ReviewsReviewIdRoute
  ReviewsIndexRoute: typeof ReviewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/': {
      id: '/reviews/'
      path: '/reviews'
      fullPath: '/reviews/'
      preLoaderRoute: typeof ReviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/$reviewId': {
      id: '/reviews/$reviewId'
      path: '/reviews/$reviewId'
      fullPath: '/reviews/$reviewId'
      preLoaderRoute: typeof ReviewsReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReviewsReviewIdRoute: ReviewsReviewIdRoute,
  ReviewsIndexRoute: ReviewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
